export type SiegeMap = {
  slug: string;
  name: string;
  location: string;
  released: string;
  category: "Ranked" | "Standard" | "Dual Front";
  isNew?: boolean;
  sites: string[];
};

export const maps: SiegeMap[] = [
  {
    slug: "calypso-casino",
    name: "Calypso Casino",
    location: "Las Vegas, Nevada",
    released: "Jun 2026",
    category: "Ranked",
    isNew: true,
    sites: ["2F Aqua / Kitchen", "2F Penthouse / High Roller", "1F Main Bar / Slots", "B Vault / Security"],
  },
  {
    slug: "fortress",
    name: "Fortress",
    location: "Morocco",
    released: "Reworked 2025",
    category: "Ranked",
    sites: ["2F Commander / Bedroom", "2F Games / Briefing", "1F Hammam / Dining", "1F Medical / Laundry"],
  },
  {
    slug: "lair",
    name: "Lair",
    location: "Portugal",
    released: "Dec 2023",
    category: "Ranked",
    sites: ["2F Master Office / R6 Room", "2F Bunks / Briefing", "1F Armory / Weapon Maintenance", "B Lab / Storage"],
  },
  {
    slug: "nighthaven-labs",
    name: "Nighthaven Labs",
    location: "Singapore",
    released: "Dec 2022",
    category: "Ranked",
    sites: ["2F Command / Server", "1F Control / Storage", "1F Kitchen / Cafeteria", "B Tank / Assembly"],
  },
  {
    slug: "emerald-plains",
    name: "Emerald Plains",
    location: "Northern Ireland",
    released: "Apr 2022",
    category: "Standard",
    sites: ["2F CEO Office / Administration", "2F Painting / Gallery", "1F Kitchen / Dining", "1F Bar / Lounge"],
  },
  {
    slug: "stadium-bravo",
    name: "Stadium Bravo",
    location: "Greece",
    released: "Sep 2022",
    category: "Standard",
    sites: ["2F Armory / Archives", "2F Penthouse / Theater", "1F Kitchen / Service", "B Workshop / Ventilation"],
  },
  {
    slug: "stadium-alpha",
    name: "Stadium Alpha",
    location: "Greece",
    released: "Jun 2020",
    category: "Standard",
    sites: ["2F Office / Meeting", "2F Bedroom / Bathroom", "1F Kitchen / Dining", "1F Piano / Living"],
  },
  {
    slug: "bank",
    name: "Bank",
    location: "Los Angeles, California",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F CEO Office / Executive Lounge", "1F Staff Room / Open Area", "1F Tellers / Archives", "B Lockers / CCTV"],
  },
  {
    slug: "border",
    name: "Border",
    location: "Middle East",
    released: "May 2016",
    category: "Ranked",
    sites: ["2F Armory / Archives", "1F Ventilation / Workshop", "1F Bathroom / Tellers", "1F Customs / Supply"],
  },
  {
    slug: "chalet",
    name: "Chalet",
    location: "Courchevel, France",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Master Bedroom / Office", "1F Bar / Gaming", "1F Kitchen / Dining", "B Wine Cellar / Snowmobile"],
  },
  {
    slug: "clubhouse",
    name: "Clubhouse",
    location: "Hanover, Germany",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Gym / Bedroom", "2F CCTV / Cash", "1F Bar / Stage", "B Church / Arsenal"],
  },
  {
    slug: "coastline",
    name: "Coastline",
    location: "Ibiza, Spain",
    released: "Feb 2017",
    category: "Standard",
    sites: ["2F Penthouse / Theater", "2F Hookah / Billiards", "1F Kitchen / Service", "1F Blue Bar / Sunrise"],
  },
  {
    slug: "consulate",
    name: "Consulate",
    location: "Abidjan, Ivory Coast",
    released: "Reworked 2023",
    category: "Ranked",
    sites: ["2F Consul Office / Meeting", "1F Lobby / Piano", "1F Exposition / Piano", "B Archives / Tellers"],
  },
  {
    slug: "kafe-dostoyevsky",
    name: "Kafe Dostoyevsky",
    location: "Moscow, Russia",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["3F Cocktail / Bar", "2F Reading / Fireplace", "2F Mining / Dining", "1F Kitchen / Service"],
  },
  {
    slug: "kanal",
    name: "Kanal",
    location: "Hamburg, Germany",
    released: "Aug 2016",
    category: "Ranked",
    sites: ["2F Server / Radar", "1F Coast Guard / Lounge", "1F Maps / Security", "B Kayaks / Supply"],
  },
  {
    slug: "oregon",
    name: "Oregon",
    location: "Redmond, Oregon",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Dorms / Kids", "1F Kitchen / Dining", "1F Meeting / Kitchen", "B Laundry / Supply"],
  },
  {
    slug: "outback",
    name: "Outback",
    location: "Australia",
    released: "Mar 2019",
    category: "Standard",
    sites: ["2F Laundry / Games", "2F Party / Office", "1F Nature / Bushranger", "1F Compressor / Gear"],
  },
  {
    slug: "skyscraper",
    name: "Skyscraper",
    location: "Nagoya, Japan",
    released: "Nov 2016",
    category: "Ranked",
    sites: ["2F Tea / Karaoke", "2F Office / Exhibition", "1F BBQ / Kitchen", "1F Bedroom / Bathroom"],
  },
  {
    slug: "theme-park",
    name: "Theme Park",
    location: "Hong Kong",
    released: "Sep 2017",
    category: "Ranked",
    sites: ["2F Initiation / Office", "2F Bunk / Daycare", "1F Armory / Throne", "1F Lab / Storage"],
  },
  {
    slug: "villa",
    name: "Villa",
    location: "Tuscany, Italy",
    released: "Jun 2018",
    category: "Ranked",
    sites: ["2F Aviator / Games", "2F Trophy / Statuary", "1F Living / Library", "1F Kitchen / Dining"],
  },
  {
    slug: "favela",
    name: "Favela",
    location: "Rio de Janeiro, Brazil",
    released: "Aug 2016",
    category: "Standard",
    sites: ["2F Coin Farm / Bunks", "2F Packaging / Meth Lab", "1F Grow Room / Lab", "1F Pink Kitchen / Pink Apartment"],
  },
  {
    slug: "hereford-base",
    name: "Hereford Base",
    location: "Herefordshire, England",
    released: "Reworked 2018",
    category: "Standard",
    sites: ["3F Tractor / Ammo", "2F Master / Kids", "1F Kitchen / Dining", "B Brewery / Fermentation"],
  },
  {
    slug: "house",
    name: "House",
    location: "Los Angeles, California",
    released: "Reworked 2020",
    category: "Standard",
    sites: ["2F Master / Office", "2F Kids / Workshop", "1F Living / Training", "B Garage / Gym"],
  },
  {
    slug: "presidential-plane",
    name: "Presidential Plane",
    location: "Heathrow, England",
    released: "Dec 2015",
    category: "Standard",
    sites: ["3F Executive / Meeting", "2F Staff / Press", "2F Luggage / Service", "1F Cargo / Storage"],
  },
  {
    slug: "tower",
    name: "Tower",
    location: "Seoul, South Korea",
    released: "Dec 2017",
    category: "Standard",
    sites: ["2F Exhibit / Office", "2F Gift Shop / Lantern", "1F Tea / Bar", "1F Restaurant / Bird"],
  },
  {
    slug: "yacht",
    name: "Yacht",
    location: "Baffin Bay",
    released: "Feb 2016",
    category: "Standard",
    sites: ["4F Cockpit / Maps", "3F Casino / Bedroom", "2F Kitchen / Engine", "1F Server / Storage"],
  },
];
