export type SiegeMap = {
  slug: string;
  name: string;
  location: string;
  released: string;
  category: "Ranked" | "Standard" | "Dual Front";
  isNew?: boolean;
  sites: string[];
};

export const maps: SiegeMap[] = [
  {
    slug: "calypso-casino",
    name: "Calypso Casino",
    location: "Las Vegas, Nevada",
    released: "Jun 2026",
    category: "Ranked",
    isNew: true,
    sites: ["2F Cigar Room / 2F Pool", "1F Blackjack / 1F Poker", "1F Bar / 1F Betting", "B CCTV / B Vault Checkpoint"],
  },
  {
    slug: "fortress",
    name: "Fortress",
    location: "Morocco",
    released: "Reworked 2025",
    category: "Ranked",
    sites: ["2F Bathroom / 2F Commander's Office", "2F Dormitory / 2F Games Room", "1F Hammam / 1F Sitting Room", "1F Waiting Room / 1F Cafeteria"],
  },
  {
    slug: "lair",
    name: "Lair",
    location: "Portugal",
    released: "Dec 2023",
    category: "Ranked",
    sites: ["2F Master Office / 2F R6 Room", "1F Bunks / 1F Briefing", "1F Armory / 1F Weapon Maintenance", "B Lab Support / B Lab"],
  },
  {
    slug: "nighthaven-labs",
    name: "Nighthaven Labs",
    location: "Singapore",
    released: "Dec 2022",
    category: "Ranked",
    sites: ["2F Command Center / 2F Servers", "1F Kitchen / 1F Cafeteria", "1F Storage / 1F Control Room", "B Assembly / B Tank"],
  },
  {
    slug: "emerald-plains",
    name: "Emerald Plains",
    location: "Northern Ireland",
    released: "Apr 2022",
    category: "Standard",
    sites: ["2F Administration / 2F CEO Office", "2F Private Gallery / 2F Meeting", "1F Bar / 1F Lounge", "1F Dining / 1F Kitchen"],
  },
  {
    slug: "stadium-bravo",
    name: "Stadium Bravo",
    location: "Greece",
    released: "Sep 2022",
    category: "Standard",
    sites: ["2F Armory / 2F Archives", "2F VIP / 2F Penthouse", "1F Kitchen / 1F Service", "1F Server / 1F Showers"],
  },
  {
    slug: "stadium-alpha",
    name: "Stadium Alpha",
    location: "Greece",
    released: "Jun 2020",
    category: "Standard",
    sites: ["2F Office / 2F Target Room", "2F Kids' Dormitory / 2F Dormitory", "1F Kitchen / 1F Dining Room", "1F Piano Room / 1F Living Room"],
  },
  {
    slug: "bank",
    name: "Bank",
    location: "Los Angeles, California",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Executive Lounge / 2F CEO Office", "1F Staff Room / 1F Open Area", "1F Tellers' Office / 1F Archives", "B Lockers / B CCTV Room"],
  },
  {
    slug: "border",
    name: "Border",
    location: "Middle East",
    released: "May 2016",
    category: "Ranked",
    sites: ["2F Armory Lockers / 2F Archives", "1F Ventilation Room / 1F Workshop", "1F Bathroom / 1F Tellers", "1F Customs Inspection / 1F Supply Room"],
  },
  {
    slug: "chalet",
    name: "Chalet",
    location: "Courchevel, France",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Master Bedroom / 2F Office", "1F Bar / 1F Gaming Room", "1F Kitchen / 1F Dining Room", "B Wine Cellar / B Snowmobile Garage"],
  },
  {
    slug: "clubhouse",
    name: "Clubhouse",
    location: "Hanover, Germany",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Gym / 2F Bedroom", "2F CCTV Room / 2F Cash Room", "1F Bar / 1F Stage", "B Church / B Arsenal Room"],
  },
  {
    slug: "coastline",
    name: "Coastline",
    location: "Ibiza, Spain",
    released: "Feb 2017",
    category: "Standard",
    sites: ["2F Penthouse / 2F Theater", "2F Hookah Lounge / 2F Billiards Room", "1F Kitchen / 1F Reception", "1F Blue Bar / 1F Sunrise Bar"],
  },
  {
    slug: "consulate",
    name: "Consulate",
    location: "Abidjan, Ivory Coast",
    released: "Reworked 2023",
    category: "Ranked",
    sites: ["2F Consul Office / 2F Meeting Room", "1F Exposition Room / 1F Piano Room", "1F Tellers / B Servers", "B Cafeteria / B Garage"],
  },
  {
    slug: "kafe-dostoyevsky",
    name: "Kafe Dostoyevsky",
    location: "Moscow, Russia",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["3F Bar / 3F Cocktail Lounge", "2F Fireplace Hall / 2F Mining Room", "2F Reading Room / 2F Fireplace Hall", "1F Kitchen Service / 1F Kitchen Cooking"],
  },
  {
    slug: "kanal",
    name: "Kanal",
    location: "Hamburg, Germany",
    released: "Aug 2016",
    category: "Ranked",
    sites: ["2F Server Room / 2F Radar Room", "1F Security Room / 1F Map Room", "1F Coast Guard Meeting Room / 1F Lounge", "B Kayaks / B Supply Room"],
  },
  {
    slug: "oregon",
    name: "Oregon",
    location: "Redmond, Oregon",
    released: "Dec 2015",
    category: "Ranked",
    sites: ["2F Kids' Dorms / 2F Dorms Main Hall", "1F Kitchen / 1F Dining Hall", "1F Meeting Hall / 1F Kitchen", "B Laundry Room / B Supply Room"],
  },
  {
    slug: "outback",
    name: "Outback",
    location: "Australia",
    released: "Mar 2019",
    category: "Standard",
    sites: ["2F Laundry Room / 2F Piano Room", "2F Party Room / 2F Office", "1F Green Bedroom / 1F Red Bedroom", "1F Mechanic Shop / 1F Kitchen"],
  },
  {
    slug: "skyscraper",
    name: "Skyscraper",
    location: "Nagoya, Japan",
    released: "Nov 2016",
    category: "Ranked",
    sites: ["2F Tea Room / 2F Karaoke", "2F Exhibition Room / 2F Work Office", "1F Kitchen / 1F BBQ", "1F Bedroom / 1F Bathroom"],
  },
  {
    slug: "theme-park",
    name: "Theme Park",
    location: "Hong Kong",
    released: "Sep 2017",
    category: "Ranked",
    sites: ["2F Initiation Room / 2F Office", "2F Bunk / 2F Day Care", "1F Armory / 1F Throne Room", "1F Lab / 1F Storage"],
  },
  {
    slug: "villa",
    name: "Villa",
    location: "Tuscany, Italy",
    released: "Jun 2018",
    category: "Ranked",
    sites: ["2F Aviator Room / 2F Games Room", "2F Trophy Room / 2F Statuary Room", "1F Living Room / 1F Library", "1F Dining Room / 1F Kitchen"],
  },
  {
    slug: "favela",
    name: "Favela",
    location: "Rio de Janeiro, Brazil",
    released: "Aug 2016",
    category: "Standard",
    sites: ["3F Packaging Room / 2F Meth Lab", "2F Football Bedroom / 2F Football Office", "2F Aunt's Bedroom / 1F Aunt's Apartment", "1F Biker's Apartment / 1F Biker's Bedroom"],
  },
  {
    slug: "hereford-base",
    name: "Hereford Base",
    location: "Herefordshire, England",
    released: "Reworked 2018",
    category: "Standard",
    sites: ["3F Ammo Storage / 3F Tractor Storage", "2F Master Bedroom / 2F Kids Room", "1F Dining Room / 1F Kitchen", "B Fermentation Chamber / B Brewery"],
  },
  {
    slug: "house",
    name: "House",
    location: "Los Angeles, California",
    released: "Reworked 2020",
    category: "Standard",
    sites: ["2F Pink Room / 2F Car Room", "2F Master Bedroom / 2F Car Room", "1F TV Room / 1F Music Room", "B Gym / B Garage"],
  },
  {
    slug: "presidential-plane",
    name: "Presidential Plane",
    location: "Heathrow, England",
    released: "Dec 2015",
    category: "Standard",
    sites: ["2F Meeting Room / 2F Executive Office", "2F Executive Bedroom / 2F Staff Section", "1F Cargo Hold / 1F Luggage Hold"],
  },
  {
    slug: "tower",
    name: "Tower",
    location: "Seoul, South Korea",
    released: "Dec 2017",
    category: "Standard",
    sites: ["2F Gift Shop / 2F Lantern Room", "2F Exhibit Room / 2F Media Center", "1F Tea Room / 1F Bar", "1F Restaurant / 1F Bird Room"],
  },
  {
    slug: "yacht",
    name: "Yacht",
    location: "Baffin Bay",
    released: "Feb 2016",
    category: "Standard",
    sites: ["4F Cockpit / 4F Maps Room", "2F Kitchen / 2F Engine Control", "2F Cafeteria / 2F Staff Dormitory", "1F Server Room / 1F Storage Room"],
  },
];
